### ISSUE TITLE
File to struct

### ISSUE THREAD

**Issue by lucabeber** [lucabeber/compito_1#6]
creazione di una funzione che legge una stringa ed acquisisce i parametri del pezzo mettendoli all'interno di una struct

**Comment by lucabeber** [comment]
@DavidLeoni Per acquisire la struttura da una stringa svg, ho deciso di inserire un commento contenente all'interno il nome del pezzo e le dimensioni in modo da facilitare l'acquisizione. E` corretto procedere in questo modo?

**Comment by DavidLeoni** [comment]
però così finisci per duplicare dati che non è mai una buona cosa, quindi se puoi cerca di prelevarli dall'svg

**Comment by lucabeber** [comment]
> però così finisci per duplicare dati che non è mai una buona cosa, quindi se puoi cerca di prelevarli dall'svg

In che senso si finisce per duplicare i dati?

**Comment by DavidLeoni** [comment]
che se le dimensioni sono ricavabili dalle tag svg per quanto possibile dovresti prenderle da quelle

se proprio risulta gravoso solo allora puoi considerare di usare il commento

**Comment by lucabeber** [comment]
> che se le dimensioni sono ricavabili dalle tag svg per quanto possibile dovresti prenderle da quelle
> 
> se proprio risulta gravoso solo allora puoi considerare di usare il commento

Ok ho capito. Ma per esempio io disegno un pistone tramite la funzione polygon, per cui i dati non sono mai presenti all' interno del svg ma si dovrebbero ricavare tramite differenza di punti. Per questo trovavo piu' comodo scrivere i dati all' interno di un commento. Ma se e' meglio ricavare i dati direttamente all' interno del svg allora provo a fare quello.
